version: '3'
services:
  miniblog2:
    build: .
    container_name: miniblog2
    ports:
      - "8018:8080"
    environment:
      - UWSGI_INI=/home/ctf/uwsgi.ini
      - NGINX_MAX_UPLOAD=1m
      - LISTEN_PORT=8080
    restart: always

